name: AWS
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:

    - name: Download ngrok
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/iamtelegramking/test1/refs/heads/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/iamtelegramking/test1/refs/heads/main/loop.bat -OutFile loop.bat

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        
    - name: Create Tunnel
      run:  | 
       Start-Process  ssh -R 3389:example.com:3389 serveo.net
       .\ngrok\ngrok.exe tcp 3389

    - name: Connect to RDP  [CPU 2 Core - 7GB Ram - 256 SSD]
      run: cmd /c start.bat
